[0;33m--- esp-idf-monitor 1.3.3 on /dev/ttyUSB0 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081534: call_start_cpu1 at /home/wtsaichu/esp/esp-idf/components/esp_system/port/cpu_start.c:182
[0m
[0;33m0x40080000: _WindowOverflow4 at /home/wtsaichu/esp/esp-idf/components/xtensa/xtensa_vectors.S:2027
[0m
[0;33m0x40080000: _WindowOverflow4 at /home/wtsaichu/esp/esp-idf/components/xtensa/xtensa_vectors.S:2027
[0m
[0;33m0x40000000: _WindowOverflow4 in ROM
[0m
[0;33m0x400facac: _GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/gcc/libstdc++-v3/libsupc++/eh_alloc.cc:462
[0m
[0;33m0x400fa720: _GLOBAL__sub_I__ZN17__eh_globals_init7_S_initE at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/gcc/libstdc++-v3/libsupc++/eh_globals.cc:162
[0m
[0;33m0x400f6b78: check_i2c_driver_conflict at /home/wtsaichu/esp/esp-idf/components/driver/i2c/i2c.c:1679
[0m
[0;33m0x400eec24: esp_ipc_init at /home/wtsaichu/esp/esp-idf/components/esp_system/esp_ipc.c:114
[0m
[0;33m0x4008d1c8: enable_timer_group0_for_calibration at /home/wtsaichu/esp/esp-idf/components/esp_hw_support/port/esp32/rtc_time.c:194
[0m
[0;33m0x400d2dbc: __esp_stack_guard_setup at /home/wtsaichu/esp/esp-idf/components/esp_system/stack_check.c:21
[0m
[0;33m0x400d2580: esp_app_format_init_elf_sha256 at /home/wtsaichu/esp/esp-idf/components/esp_app_format/esp_app_desc.c:68
[0m
[0;33m0x400d6a34: __esp_system_init_fn_esp_timer_startup_init at /home/wtsaichu/esp/esp-idf/components/esp_timer/src/esp_timer.c:578
[0m
[0;33m0x4010ac1c: __esp_system_init_fn_init_components0 at /home/wtsaichu/esp/esp-idf/components/esp_system/startup.c:470
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x40081534: call_start_cpu1 at /home/wtsaichu/esp/esp-idf/components/esp_system/port/cpu_start.c:182
[0m
[0;33m0x40080000: _WindowOverflow4 at /home/wtsaichu/esp/esp-idf/components/xtensa/xtensa_vectors.S:2027
[0m
[0;33m0x40080000: _WindowOverflow4 at /home/wtsaichu/esp/esp-idf/components/xtensa/xtensa_vectors.S:2027
[0m
[0;33m0x40000000: _WindowOverflow4 in ROM
[0m
[0;33m0x400facac: _GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/gcc/libstdc++-v3/libsupc++/eh_alloc.cc:462
[0m
[0;33m0x400fa720: _GLOBAL__sub_I__ZN17__eh_globals_init7_S_initE at /builds/idf/crosstool-NG/.build/xtensa-esp-elf/src/gcc/libstdc++-v3/libsupc++/eh_globals.cc:162
[0m
[0;33m0x400f6b78: check_i2c_driver_conflict at /home/wtsaichu/esp/esp-idf/components/driver/i2c/i2c.c:1679
[0m
[0;33m0x400eec24: esp_ipc_init at /home/wtsaichu/esp/esp-idf/components/esp_system/esp_ipc.c:114
[0m
[0;33m0x4008d1c8: enable_timer_group0_for_calibration at /home/wtsaichu/esp/esp-idf/components/esp_hw_support/port/esp32/rtc_time.c:194
[0m
[0;33m0x400d2dbc: __esp_stack_guard_setup at /home/wtsaichu/esp/esp-idf/components/esp_system/stack_check.c:21
[0m
[0;33m0x400d2580: esp_app_format_init_elf_sha256 at /home/wtsaichu/esp/esp-idf/components/esp_app_format/esp_app_desc.c:68
[0m
[0;33m0x400d6a34: __esp_system_init_fn_esp_timer_startup_init at /home/wtsaichu/esp/esp-idf/components/esp_timer/src/esp_timer.c:578
[0m
[0;33m0x4010ac1c: __esp_system_init_fn_init_components0 at /home/wtsaichu/esp/esp-idf/components/esp_system/startup.c:470
[0m
[1;31mNone[0m
[0;33mWaiting for the device to reconnect[0mException in thread Thread-2 (_run_outer):
Traceback (most recent call last):
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 76, in run
    data = self.serial.read(self.serial.in_waiting or 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 83, in run
    self.close_serial()
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 120, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/stoppable_thread.py", line 47, in _run_outer
    self.run()
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 100, in run
    self.close_serial()
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 104, in close_serial
    self._disable_closing_wait_or_discard_data()
  File "/home/wtsaichu/.espressif/python_env/idf5.3_py3.11_env/lib/python3.11/site-packages/esp_idf_monitor/base/serial_reader.py", line 120, in _disable_closing_wait_or_discard_data
    buf = fcntl.ioctl(self.serial.fd, termios.TIOCGSERIAL, buf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error
[0m
